variables:
  dockerId: avasiu
  appName: musifyapi
  imageName: musify

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls -lah
  displayName: 'Display work Directory'
- script: docker login -u $(dockerId) -p $(pswd)
  displayName: 'Docker Login'
- script: docker build -t $(appName).azurecr.io/$(imageName) .
  displayName: 'Build Docker Image'
- script: docker push $(appName).azurecr.io/$(imageName)

