variables:
  dockerId: avasiu

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls -lah
  displayName: 'Display work Directory'
- script: docker login -u $(dockerId) -p $(pswd)
  displayName: 'Docker Login'
- script: docker build Dockerfile
  displayName: 'Build Docker Image'

